version: '3.5'

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    volumes:
      - ./qdrant_storage:/qdrant/storage
      - ./qdrant_snapshots:/qdrant/snapshots
    ports: 
      - "6333:6333"